//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedDragonCardCatcher.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Enums {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Enums() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RedDragonCardCatcher.Common.Resources.Enums", typeof(Enums).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying data..
        /// </summary>
        internal static string Enum_OperationStatus_Computing {
            get {
                return ResourceManager.GetString("Enum_OperationStatus_Computing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying data..
        /// </summary>
        internal static string Enum_OperationStatus_Copying {
            get {
                return ResourceManager.GetString("Enum_OperationStatus_Copying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading data..
        /// </summary>
        internal static string Enum_OperationStatus_Downloading {
            get {
                return ResourceManager.GetString("Enum_OperationStatus_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading data..
        /// </summary>
        internal static string Enum_OperationStatus_Getting {
            get {
                return ResourceManager.GetString("Enum_OperationStatus_Getting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Enum_OperationStatus_None {
            get {
                return ResourceManager.GetString("Enum_OperationStatus_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpacking data..
        /// </summary>
        internal static string Enum_OperationStatus_Unzipping {
            get {
                return ResourceManager.GetString("Enum_OperationStatus_Unzipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading failed. Couldn&apos;t connect to server..
        /// </summary>
        internal static string Enum_UpdaterError_AppInfoLoadingFailed {
            get {
                return ResourceManager.GetString("Enum_UpdaterError_AppInfoLoadingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying failed. Couldn&apos;t verify data..
        /// </summary>
        internal static string Enum_UpdaterError_ComputingHashingFailed {
            get {
                return ResourceManager.GetString("Enum_UpdaterError_ComputingHashingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying failed..
        /// </summary>
        internal static string Enum_UpdaterError_CopyingFailed {
            get {
                return ResourceManager.GetString("Enum_UpdaterError_CopyingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading failed. Server sent invalid data..
        /// </summary>
        internal static string Enum_UpdaterError_DeserializingFailed {
            get {
                return ResourceManager.GetString("Enum_UpdaterError_DeserializingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading failed..
        /// </summary>
        internal static string Enum_UpdaterError_DownloadingFailed {
            get {
                return ResourceManager.GetString("Enum_UpdaterError_DownloadingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading failed. Invalid server name..
        /// </summary>
        internal static string Enum_UpdaterError_InvalidAppInfoPath {
            get {
                return ResourceManager.GetString("Enum_UpdaterError_InvalidAppInfoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying failed. Data is invalid..
        /// </summary>
        internal static string Enum_UpdaterError_InvalidHash {
            get {
                return ResourceManager.GetString("Enum_UpdaterError_InvalidHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading failed. Server sent invalid data..
        /// </summary>
        internal static string Enum_UpdaterError_InvalidXmlFormat {
            get {
                return ResourceManager.GetString("Enum_UpdaterError_InvalidXmlFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error..
        /// </summary>
        internal static string Enum_UpdaterError_Unexpected {
            get {
                return ResourceManager.GetString("Enum_UpdaterError_Unexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpacking failed..
        /// </summary>
        internal static string Enum_UpdaterError_UnzippingFailed {
            get {
                return ResourceManager.GetString("Enum_UpdaterError_UnzippingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying failed. Certificate is invalid..
        /// </summary>
        internal static string Enum_UpdaterError_VerifyingFailed {
            get {
                return ResourceManager.GetString("Enum_UpdaterError_VerifyingFailed", resourceCulture);
            }
        }
    }
}
