//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedDragonCardCatcher.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Notifications {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Notifications() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RedDragonCardCatcher.Common.Resources.Notifications", typeof(Notifications).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriveHUD cannot load a HUD since the table was open prior to DriveHUD being loaded. DriveHUD needs to be loaded first, then a table for Red Dragon can be loaded..
        /// </summary>
        internal static string Notifications_HudLayout_PreLoadingText_CanNotBeCapturedText {
            get {
                return ResourceManager.GetString("Notifications_HudLayout_PreLoadingText_CanNotBeCapturedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One full hand must be played before HUD appears. Please wait..
        /// </summary>
        internal static string Notifications_HudLayout_PreLoadingText_Init {
            get {
                return ResourceManager.GetString("Notifications_HudLayout_PreLoadingText_Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUD can&apos;t be loaded. Red Dragon Card Catcher License doesn&apos;t support this table..
        /// </summary>
        internal static string Notifications_HudLayout_PreLoadingText_NoLicense {
            get {
                return ResourceManager.GetString("Notifications_HudLayout_PreLoadingText_NoLicense", resourceCulture);
            }
        }
    }
}
